In [22]:
import numpy as np

In [1]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

## 5.1 pandas 자료구조 소개 

### 5.1.1 Series 

Series는 객체를 담을 수 있는 1차원 배열 같은 자료구조<br>
index라는 배열의 데이터와 연괸된 이름을 가지고 있음 

In [4]:
obj = pd.Series([4, 7, -5, 3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

```python
# index : 0 ~ N-1(데이터 길이 : N)
index(0)          value
index(1)          value
index(2)          value
             .
             .
             .
index(N-1)        value
dtype: 
```

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index # range(4) 와 같음

RangeIndex(start=0, stop=4, step=1)

In [13]:
# index를 지칭
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])

In [11]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2.index 

Index(['d', 'b', 'a', 'c'], dtype='object')

index로 라벨을 사용할 수 있음 

In [14]:
obj2['a']

-5

In [15]:
obj2['d'] = 6

In [17]:
#index 배열 
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [19]:
# 배열 연산 수행해도 index - value 유지 
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [20]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [25]:
# exp() --> 지수(e)함수
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Series = 고정 길이의 정렬된 dictionary type 

In [26]:
'b' in obj2 

True

In [27]:
'e' in obj2 

False

In [28]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [29]:
# dicionary --> Series
obj3 = pd.Series(sdata)

In [30]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [31]:
# index 순서 지정
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [32]:
obj4 = pd.Series(sdata, index = states)

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [36]:
# 누락된 데이터 
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [37]:
# 누락되지 않는 데이터
pd.notnull(obj4)


California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [39]:
# pd.isnull(obj4)와 동일 
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [41]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [42]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [44]:
# index와 values 자동정렬 
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [45]:
# name 속성
obj4.name = 'population' 

In [46]:
obj4.index.name = 'state'

In [47]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [48]:
obj 

0    4
1    7
2   -5
3    3
dtype: int64

In [49]:
# index 변경
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [50]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame

DataFrame은 표같은 스프레드시트 형식의 자료구조<br>
여러 개의 컬럼이 존재, 각 컬럼에 서로 다른 종류의 값(숫자, 문자열, 불리언 등)을 담을 수 있음.<br>
DataFrame은 row(열, 가로) 와 column(행, 세로)으로 구성되어 있으며 row 와 column에 대한 색인이 존재<br>

In [53]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [54]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [55]:
# head 메서드 : 처음 5개의 row만 출력 가능
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [56]:
# columns를 지정
pd.DataFrame(data, columns= ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [59]:
# debt : 존재하지 않는 값 --> NaN
frame2= pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'], index = ['one', 'two', 'three', 'four', 'five', 'six'])

In [58]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [60]:
# DataFrame의 columns : dictionary 형식의 표기법으로 접근 or 속성 형식으로 접근
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [61]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [62]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [63]:
# columns에 대입
frame2['debt'] = 16.5

In [64]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [68]:
# numpy.arange([start, ] stop, [step, ] dtype=None)
frame2['debt'] = np.arange(6.)

In [67]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [70]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

In [73]:
# Series를 DataFrame에 대입
frame2['debt'] = val

In [72]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [74]:
# 새로운 column 생성
frame2['eastern'] = frame2.state == 'Ohio'

In [75]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [76]:
# del 예약어를 이용한 column 삭제
del frame2['eastern']

In [77]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [86]:
# 중첩 dictionary를 이용해 데이터 생성
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 3.6}}

In [90]:
# 바깥에 있는 key -> column, 안에 있는 key -> row
frame3 = pd.DataFrame(pop)

In [91]:
frame3

Nevada  Ohio
2001     2.4   3.6
2002     2.9   NaN
2000     NaN   1.5

In [89]:
# 데이터 전치(Transfer)
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     3.6   NaN   1.5

In [92]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
         'Nevada' : frame3['Nevada'][:2]}

In [93]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   3.6     2.4
2002   NaN     2.9

In [94]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [95]:
frame3

state  Nevada  Ohio
year               
2001      2.4   3.6
2002      2.9   NaN
2000      NaN   1.5

In [96]:
# values : DataFrame에 저장된 데이터를 2차원 배열로 반환
frame3.values

array([[2.4, 3.6],
       [2.9, nan],
       [nan, 1.5]])

In [98]:
# 모든 데이터 타입을 수용하는 배열의 dtype이 선택
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 5.1.3 Index Objects

Index Objects : 표 형식의 데이터에서 각 row와 columns에 대한 이름과 다른 메타데이터를 저장하는 객체 

In [99]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])

In [100]:
index = obj.index 

In [101]:
index

Index(['a', 'b', 'c'], dtype='object')

In [102]:
index[1:]

Index(['b', 'c'], dtype='object')

```python
# index 변경 불가 
index[1] = 'd' #TypeError

In [104]:
labels = pd.Index(np.arange(3))

In [105]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [106]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [107]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [108]:
obj2.index is labels

True

In [109]:
frame3

state  Nevada  Ohio
year               
2001      2.4   3.6
2002      2.9   NaN
2000      NaN   1.5

In [113]:
# Index objects 고정 크기로 작동
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [111]:
'Ohio' in frame3.columns

True

In [112]:
2003 in frame3.index 

False

In [114]:
# pandas index는 중복되는 값 허용
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [115]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 핵심 기능 

### 5.2.1 Reindexing

새로운 index에 맞도록 객체를 새로 생성 

In [116]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])

In [117]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [118]:
# reindexing
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [119]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [120]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])

In [121]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [123]:
# ffil method (누락된 값 <- 직전의 값)
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

DataFrame : reindex는 row(index), column 또는 둘 다 변경 가능 (단, 순서만 전달 -> row reindex) 

In [164]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a','c','d'],
                    columns = ['Ohio', 'Texas', 'California'])

In [155]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [156]:
# reindex
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [157]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [158]:
states = ['Texas', 'Utah', 'California']

In [159]:
# columns 예약어 이용하여 reindex
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 5.2.2 하나의 row나 column 삭제하기 

삭제하기 위해서는 데이터 모양을 변경하는 작업이 필요<br>
drop method : 선택한 값들이 삭제된 새로운 객체를 얻을 수 있음

In [172]:
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])

In [173]:
obj 

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [177]:
# Series에서 삭제
new_obj = obj.drop('c')

In [175]:
new_obj 

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [176]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [179]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns = ['one','two', 'three', 'four'])

In [180]:
data 

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [181]:
# DataFrame row 삭제
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [183]:
# DataFrame columns 삭제 (method1. axis = 1)
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [184]:
# DataFrame columns 삭제 (method2. axis = 'columns')
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [185]:
# 원본 객체 변경
obj.drop('c', inplace = True)

In [186]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64