In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 31.2 ms
Wall time: 20.3 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 906 ms
Wall time: 896 ms


## 4.1 NumPy ndarray: 다차원 배열 객체 

##### ndarray : 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열 

In [6]:
import numpy as np

In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[ 2.79148111,  0.29676186, -1.47801115],
       [-0.06089723, -1.52948489, -0.11424929]])

In [9]:
data * 10

array([[ 27.91481106,   2.96761865, -14.78011149],
       [ -0.60897231, -15.29484894,  -1.14249294]])

In [10]:
data + data

array([[ 5.58296221,  0.59352373, -2.9560223 ],
       [-0.12179446, -3.05896979, -0.22849859]])

In [12]:
# shape : 차원을 알려주는 객체 
data.shape

(2, 3)

In [13]:
# dtype : 튜플과 배열에 저장된 자료형을 알려주는 객체
data.dtype

dtype('float64')

### 4.1.1 ndarray 생성하기 
배열 생성 --> array 함수 이용 

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int32')

In [25]:
# zeros : 주어진 길이나 모양에 0이 들어있는 배열 생성
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [29]:
# ones : 주어진 길이난 모양에 1이 들어있는 배열 생성
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [34]:
# arrange : 파이썬의 range 함수의 배열 버전
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##### 배열 생성 함수
array : 입력 데이터를 ndarray로 변환, 입력 데이터 복사<br>
asarray : 입력 데이터를 ndarray로 변환하지만 입력 데이터가 이미 ndarray일 경우 복사가 일어나지 않음<br>
arange : 내장 함수 range와 유사하지만 ndarray로 반환<br>
ones, ones_like : 배열 내용을 1로 초기화, ones_like는 주어진 배열과 동일한 모양과 dtype을 가지는 배열을 새로 생성하여 1로 초기화<br>
zeros, zeros_like : ones, ones_like와 동일, 0으로 초기화<br>
empty, empty_like : 메모리 할당하여 새로운 배열 생성, 초기화 x<br>
full, full_like : 인자로 받은 dtype과 배열의 모양을 가지는 배열을 생성 + 인자로 받은 값으로 배열을 채<br>
eye, identity : N * N 크기의 단위행열 생성(좌상단->우하단 대각선 : 1, 나머지는 0으로 초기화)<br>

### 4.1.2 ndarray와 dtype

In [36]:
ar1 = np.array([1, 2, 3], dtype = np.float64)

In [38]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [39]:
arr1.dtype

dtype('float64')

In [40]:
arr2.dtype

dtype('int32')

In [41]:
arr = np.array([1, 2, 3, 4, 5])

In [42]:
arr.dtype

dtype('int32')

In [50]:
# astype 메서드를 사용해 배열의 dtype을 다른 형으로 변환 
float_arr = arr.astype(np.float64)

In [45]:
float_arr.dtype

dtype('float64')

In [46]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [47]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [48]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [52]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [53]:
# astype : 숫자 형식의 문자열을 담고 있는 배열 -> 숫자로 변환
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [55]:
int_array = np.arange(10)

In [56]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)

In [58]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [59]:
empty_uint32 = np.empty(8, dtype = 'u4')

In [62]:
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)